# Generated by Django 5.0.6 on 2024-08-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='comision',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
